# System Configuration
system:
  arxiv_topics:
    "Computer Science": "cs"
    "Mathematics": "math"
    "Physics": "physics"
    "Quantitative Biology": "q-bio"
    "Quantitative Finance": "q-fin"
    "Statistics": "stat"
    "Electrical Engineering": "eess"
    "Economics": "econ"
  
  physics_subtopics:
    "Astrophysics": "astro-ph"
    "Condensed Matter": "cond-mat"
    "General Relativity": "gr-qc"
    "High Energy Physics - Experiment": "hep-ex"
    "High Energy Physics - Theory": "hep-th"
    "Mathematical Physics": "math-ph"
    "Nuclear Theory": "nucl-th"
    "Quantum Physics": "quant-ph"

# User Configuration
user:
  topic: "Computer Science"
  categories: [
    "Artificial Intelligence", 
    "Computation and Language", 
    "Machine Learning"
  ]

# Model Configuration
model:
  name: "gpt-4"
  provider: "openai"
  papers_per_batch: 8
  temperature: 0.7
  threshold: 7.5  # Relevance score threshold (1-10)

# Interest Profile
interest: |
  I am an applied AI engineer focused on implementing LLM-based solutions for business problems...
